[package]
name = "css-in-rust"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[dependencies]
css-rs-macro = { path = "../../crates/css-rs-macro" }
virtual-dom-rs = { path = "../../crates/virtual-dom-rs" }
