[package]
name = "html-macro"
version = "0.0.1"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.11"
syn = { version = "0.15", features = ["full", "extra-traits"] }
