[package]
name = "isomorphic-client"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
isomorphic-app = { path = "../app" }

[dependencies.wasm-bindgen]
git = "https://github.com/rustwasm/wasm-bindgen"
features = ["default", "nightly"]
