[package]
name = "isomorphic-server"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
private = true

[dependencies]
virtual-dom-rs = { path = "../../../" }
isomorphic-app = { path = "../app" }
