[package]
name = "isomorphic-server"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
publish = false

[dependencies]
virtual-dom-rs = { path = "../../../crates/virtual-dom-rs" }
isomorphic-app = { path = "../app" }
actix-web = "0.7"
listenfd = "0.3"
